---
- name: Listen for events on a webhook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: "{{ webhook_port }}"

  rules:
    - name: Create Redmine issue ticket
      condition: >
        event.payload.trigger_name == "Failed to connect web server"
        and event.payload.event_severity == "High"
      action:
        run_workflow_template:
          name: "{{ student_name }}: AIOps simple workflow"
          organization: Default
          job_args:
            extra_vars:
              payload: "{{ event.payload }}"
