---
- name: Redmine create ticket
  hosts: all
  gather_facts: false

  tasks:

    - name: Send request to Gemini API
      delegate_to: localhost
      no_log: true
      register: gemini_response
      ansible.builtin.uri:
        url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
        method: POST
        headers:
          x-goog-api-key: "{{ gemini_api_key }}"
          Content-Type: application/json
        body_format: json
        body:
          system_instruction:
            parts:
              - text: "{{ gemini_prompt['instruction'] }}"
          contents:
            - role: user
              parts:
                - text: |-
                    {{ gemini_prompt['contents'] }}
                    {{ payload | to_nice_json }}
        status_code: 200

    - name: Show the Gemini response
      ansible.builtin.debug:
        var: gemini_response.json.candidates[0].content.parts[0].text

    - name: Create issue
      delegate_to: localhost
      register: ret
      ansible.builtin.uri:
        url: http://{{ redmine_host }}:3000/issues.json
        method: POST
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ redmine_api_key }}"
        body_format: json
        body:
          issue:
            project_id: aiops
            tracker_id: 1
            subject:  Error occurred {{ student_name }} - on {{ payload.host_host }} - {{ payload.trigger_name }} - {{ payload.event_severity }}
            description: "{{ gemini_response.json.candidates[0].content.parts[0].text }}"
        return_content: true
        status_code:
          - 200
          - 201

    - name: Show result
      ansible.builtin.debug:
        var: gemini_response.json.candidates[0].content.parts[0].text
             | regex_search('(?s)^# webserver_recovery.yml.*?^\\.\\.\\.', multiline=True)

    - name: Set playbook stats
      ansible.builtin.set_stats:
        data:
          playbook_content: "{{ gemini_response.json.candidates[0].content.parts[0].text | regex_search('(?s)^# webserver_recovery.yml.*?^\\.\\.\\.', multiline=True) }}"
          playbook_name: webserver_recovery.yml
        aggregate: false
