---
- name: Redmine create ticket
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Send request to Gemini API
      no_log: true
      register: gemini_response
      ansible.builtin.uri:
        url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
        method: POST
        headers:
          x-goog-api-key: "{{ gemini_api_key }}"
          Content-Type: application/json
        body_format: json
        body:
          system_instruction:
            parts:
              - text: "あなたは優秀なITインフラエンジニアであり、Ansible Playbook開発者です。以下の情報をもとにRedmineのチケットを作成してください。"
          contents:
            - role: user
              parts:
                - text: "監視システムZabbixからのWeb監視(URL)アラート情報をもとに、起きている問題と診断、解決のためのPlaybookを提示してください。YAMLファイルの1行目は「# webserver_recovery.yml)」で始め、あとはYAML記法通り、「---」で始めて「...」で終了し、全体をコードブロックとして扱ってください。以下はアラートの詳細情報です。\n{{ payload }}"
        status_code: 200

    - name: Show the Gemini response
      ansible.builtin.debug:
        var: gemini_response.json.candidates[0].content.parts[0].text

    - name: Create issue
      register: ret
      ansible.builtin.uri:
        url: http://{{ redmine_host }}:3000/issues.json
        method: POST
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ redmine_api_key }}"
        body_format: json
        body:
          issue:
            project_id: eda
            tracker_id: 1
            subject: Error occurred on {{ payload.host_host }} - {{ payload.trigger_name }} - {{ payload.event_severity }}
            description: "{{ gemini_response.json.candidates[0].content.parts[0].text }}"
        return_content: true
        status_code:
          - 200
          - 201

    - name: Show result
      ansible.builtin.debug:
        var: gemini_response.json.candidates[0].content.parts[0].text
             | regex_search('(?s)# webserver_recovery.yml.*?\\.\\.\\.', multiline=True)

    - name: Copy file
      ansible.builtin.copy:
        content: "{{ gemini_response.json.candidates[0].content.parts[0].text | regex_search('(?s)# webserver_recovery.yml.*?\\.\\.\\.', multiline=True) }}"
        dest: "./webserver_recovery.yml"
        mode: '0644'

    - name: Show the file content
      ansible.builtin.debug:
        var: lookup('file', './webserver_recovery.yml')

    - name: Clone git repository
      register: git_clone_result
      ansible.scm.git_retrieve:
        branch:
          name: main
          duplicate_detection: false
        origin: 
          url: "{{ git_repo_url }}"

    - name: Copy the file to the current directory
      ansible.builtin.copy:
        src: "./webserver_recovery.yml"
        dest: "{{ git_clone_result['path'] }}/webserver_recovery.yml"
        mode: '0644'

    - name: Publish the changes
      register: git_push_result
      ansible.scm.git_publish:
        path: "{{ git_clone_result['path'] }}"

    
    - name: Show the file content
      ansible.builtin.debug:
        var: git_push_result