---
- name: Redmine create ticket
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Send request to Gemini API
      no_log: true
      register: gemini_response
      ansible.builtin.uri:
        url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
        method: POST
        headers:
          x-goog-api-key: "{{ gemini_api_key }}"
          Content-Type: application/json
        body_format: json
        body:
          contents:
            - parts:
                - text: "{{ user_question }}"
        status_code: 200

    - name: Show the Gemini response
      ansible.builtin.debug:
        var: gemini_response.json.candidates[0].content.parts[0].text


    - name: Create issue
      register: ret
      ansible.builtin.uri:
        url: http://ec2-16-176-29-186.ap-southeast-2.compute.amazonaws.com:3000/issues.json
        method: POST
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ redmine_api_key }}"
        body_format: json
        body:
          issue:
            project_id: eda
            tracker_id: 1
            subject: Error occurred on {{ payload.host_host }} - {{ payload.trigger_name }} - {{ payload.event_severity }}
            description: gemini_response.json.candidates[0].content.parts[0].text
        return_content: true
        status_code:
          - 200
          - 201

    - name: Show result
      ansible.builtin.debug:
        var: ret
