---
- name: Remediation Playbook
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Update AAP Project
      ansible.controller.project_update:
        project: genai-playbooks
        timeout: 60

    - name: Create a new job template
      ansible.controller.job_template:
        name: Webserver Recovery
        project: genai-playbooks
        playbook: "{{ playbook_name }}"
        inventory: example-aiops
        credentials:
          - linux

    - name: Run the job template
      register: job_launch_result
      ansible.controller.job_launch:
        job_template: Webserver Recovery

    - name: Wait for the job to complete
      ansible.controller.job_wait:
        job_id: "{{ job_launch_result.id }}"
        timeout: 300

    - name: Show the job launch result
      ansible.builtin.debug:
        var: job_launch_result