---
- name: Remediation Playbook
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Create a new job template
      delegate_to: localhost
      ansible.controller.job_template:
        name: "{{ jt_name }}"
        project: genai-playbooks
        playbook: "{{ playbook_name }}"
        inventory: example-aiops
        credentials:
          - linux

    - name: Run the job template
      delegate_to: localhost
      register: job_launch_result
      ansible.controller.job_launch:
        job_template: "{{ jt_name }}"

    - name: Wait for the job to complete
      delegate_to: localhost
      ansible.controller.job_wait:
        job_id: "{{ job_launch_result.id }}"
        timeout: 300
