---
- name: Show playbook content
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Show the playbook content
      ansible.builtin.debug:
        var: playbook_content