---
- name: Toggle Web Server Service
  hosts: student
  gather_facts: false

  tasks:

    - name: Check if httpd is running
      ansible.builtin.service_facts:

    - name: Toggle httpd service
      become: true
      ansible.builtin.service:
        name: httpd.service
        state: "{{ 'stopped' if 'httpd.service' in services and services['httpd.service'].state == 'running' else 'started' }}"